apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: platform-network-external-services
spec:
  hosts:
  - "*"
  gateways:
  - http-gateway                      # 1
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: platform-network
        port:
          number: 80
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - POST
      - OPTIONS
      - GET
      allowHeaders:
      - Access-Control-Allow-Origin
      - authorization
      - content-type
      - accept
      - origin
      - user-agent
      exposeHeaders:
      - x-custom-header
      maxAge: 300s
      allowCredentials: true   
       