apiVersion: "rbac.istio.io/v1alpha1"
kind: RbacConfig
metadata:
  name: default
spec:
  mode: 'ON_WITH_INCLUSION'                     # 1
  inclusion:
    services:                                   # 2
    - "pn-frontend.default.svc.cluster.local"
    - "pn-web-app.default.svc.cluster.local" 
    - "pn-feedback.default.svc.cluster.local"   
